server:
  port: 9090
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:8080/myapp
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin
      password: 

